apiVersion: apps/v1
kind: Deployment
metadata:
  name: three-tier-app-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: three-tier-app-frontend
  template:
    metadata:
      labels:
        app: three-tier-app-frontend
    spec:
      containers:
      - name: three-tier-app-frontend
        image: surajmane121045/three_tier_app_frontend:dbcff1ae4cc3ad407bbe3ebefa229c76361c71a8
        ports:
        - containerPort: 80
