apiVersion: apps/v1
kind: Deployment
metadata:
  name: three-tier-app-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: three-tier-app-frontend
  template:
    metadata:
      labels:
        app: three-tier-app-frontend
    spec:
      containers:
      - name: three-tier-app-frontend
        image: surajmane121045/three_tier_app_frontend:87173d7434a53e47af0db4f430a6598e68e690f8
        ports:
        - containerPort: 80
